Simplify the current CI/CD workflow
EVerest/everest-demo pull request #10
Opened 2023-11-29 23:02 UTC by drmrd

2023-12-01 04:12 UTC, shankari commented on .github/workflows/cicd.yaml
> +            type=semver,pattern=${{ steps.docker-image-version-check.SEMVER }}
can you articulate your reasons for preferring the manually updated `semver` to a more automatically generated unique tag based on date/time or timestamp?

2023-12-02 00:58 UTC, drmrd commented on .github/workflows/cicd.yaml
> +            type=semver,pattern=${{ steps.docker-image-version-check.SEMVER }}
@shankari: Sure! I've also added a description to this PR that covers my rationale. My main goal in making these changes is to

1. get past issues we're experiencing with the `build_pkg_*`-based workflow so that we can merge the other Task 1 PRs in this repo and update our images
2. while avoiding introducing the chicken-and-egg problem you had concerns over with our first pass CI/CD workflow (from our old private fork).
    - The chicken-and-egg problem I'm referring to: Our Docker Compose files reference images defined by `Dockerfile`s in the same repository. If our CI/CD pipeline only builds and pushes updated Docker images (with new semver tags) after we have merged changes into `main`, we either have to then update our Docker Compose files in a separate PR (which is time consuming and more overhead for devs and reviewers) or accept that our Docker Compose files will temporarily reference Docker images that don't exist (until the CI/CD pipeline finishes building and pushing them).

The advantage here is that we can set the tags for our Docker images manually to a new version as part of our PRs and have the updated images built before a PR is merged. When a PR is merged, the most recent image builds from the PR will be available either immediately or worst case (if another PR was using the same updated tag and clobbered this PR's builds in the Registry) within a few minutes.

2023-12-02 01:00 UTC, drmrd commented on .github/workflows/cicd.yaml
> +            type=semver,pattern=${{ steps.docker-image-version-check.SEMVER }}
It's not an elegant solution long-term, but this also starts the process of moving these images into the EVerest organization and sets us up for future refactors that simplify the build process if we ever move the `Dockerfile`s in this repo into a more logical location within the org.

2023-12-04 07:20 UTC, shankari commented
>  Test the new workflow in US-JOET? I will work on this early next week. Given the lack of a functioning Docker image-building CI/CD pipeline for this repo, I propose merging changes here and addressing any issues in fast follow-up PRs to this repository if testing in US-JOET proves time-consuming.

I requested, and have received, have write access to this repo temporarily while the working groups, and their permissions, are sorted out. Given that permission, I don't think we need to have this work on US-JOET. We are "upstream first" and the image builds on US-JOET were just a stopgap to deal with the lack of permission here.

2023-12-04 07:28 UTC, shankari requested changes
I'm approving the workflow anyway, but I expect it to fail, given that we are trying to build `us-joet` images through a workflow in the `everest` org.

2023-12-04 07:28 UTC, shankari commented on .github/workflows/cicd.yaml
> +          - host_namespace: ghcr.io/us-joet/everest-demo
I think these will need to be `everest` instead of `us-joet` given that this is the everest repo and we are creating the images here.

2023-12-04 07:28 UTC, shankari commented on docker-compose.admin-panel.yml
> +    image: ghcr.io/everest/everest-demo/mqtt-server:0.0.3
> The version specified in .docker_image_version should also match the version of each image in our Docker Compose files going forward.

Is the expectation that these would all be updated manually? It seems like an environment variable and/or common env file with the semver to use would be better.

2023-12-04 16:49 UTC, drmrd commented on .github/workflows/cicd.yaml
> +          - host_namespace: ghcr.io/us-joet/everest-demo
Bah! I thought I'd updated all of the image namespaces. Thanks for catching these. I've updated them.

2023-12-04 17:22 UTC, shankari approved these changes
LGTM! I am not going to hold up approval for this, but can you comment on
https://github.com/EVerest/everest-demo/pull/10#issuecomment-1838896131
before I merge 😄

2023-12-04 19:36 UTC, drmrd commented
> LGTM! I am not going to hold up approval for this, but can you comment on [#10 (comment)](https://github.com/EVerest/everest-demo/pull/10#issuecomment-1838896131) before I merge 😄

Will do! Thanks @shankari!

2023-12-05 00:34 UTC, drmrd commented on docker-compose.admin-panel.yml
> +    image: ghcr.io/everest/everest-demo/mqtt-server:0.0.3
Great suggestion. Since it involved modifying the demo one-liners, I had planned to punt on this, but I've gone ahead and migrated from a `.docker_image_version` file to a `.env` that's also used in our Compose files.

2023-12-05 00:46 UTC, drmrd commented
> > This also means that squash-and-merge is the only merge strategy for the repository that will avoid pre-release image versions appearing in main.
> 
> I'm not sure why squash-and-merge would make any difference. Concretely:
> 
>     * the GitHub action runs on every pull request to main (aka every update to a pull request)
> 
>     * if the developer has set the image version to `0.0.4-my-new-feature`, then the action will go ahead and create an image with a tag `0.0.4-my-new-feature`

This is what I was referring to as a pre-release image. Using a rebase-and-merge strategy will result in a commit on the `main` branch that references an image tagged `0.0.4-my-new-feature`, which isn't ideal.

> It seems like the real issue is with pushing images on the pull request. What we really want is:
> 
>     * build images + future extension to run automated tests on PR
> 
>     * build + test + push images on branch push and/or tag/release creation

I agree this is the ideal. In our older private fork, we briefly had a pipeline set up like this before changing gears. I'm happy to remove the pushes on PRs here, but note that even with caching there can be a brief post-merge period during which Docker Compose files will point to images that don't exist in GHCR. Is this still a concern?

I'll plan to keep the push-on-PR portion of the workflow in tact for now but am happy to remove it later.

2023-12-05 01:55 UTC, drmrd commented
@caller: We're encountering a permissions issue when pushing images to GHCR from this repo's GitHub Actions workflow. Could you confirm that default permissions for the `GITHUB_TOKEN` in the EVerest organization are permissive (both read and write) as discussed [here](https://docs.github.com/en/organizations/managing-organization-settings/disabling-or-limiting-github-actions-for-your-organization#setting-the-permissions-of-the-github_token-for-your-organization)?

2023-12-05 02:00 UTC, drmrd commented
@shankari: Could you verify that this repo's workflows are allowed to write to GHCR as discussed [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions)?

2023-12-05 04:04 UTC, shankari commented
@hikinggrass for visibility
@drmrd I have write permission on the repo, not admin. I don't see the settings.
Note however that we do have permissions in the workflow
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

```
jobs:
  docker-build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
```

and that was good enough for us-joet

2023-12-05 04:05 UTC, shankari commented
I do note that you cannot grant write permissions to forked repos
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token

> You can use the permissions key to add and remove read permissions for forked repositories, but typically you can't grant write access. The exception to this behavior is where an admin user has selected the Send write tokens to workflows from pull requests option in the GitHub Actions settings.

2023-12-05 04:11 UTC, shankari commented
I checked the us-joet settings, and we do have restrictive permissions for the repo

<img width="924" alt="Screen Shot 2023-12-04 at 8 07 43 PM" src="https://github.com/EVerest/everest-demo/assets/2423263/99aed263-b36f-4918-a548-c22eadf75c49">

and the org

<img width="924" alt="Screen Shot 2023-12-04 at 8 10 44 PM" src="https://github.com/EVerest/everest-demo/assets/2423263/4cd06671-fa48-49d1-ab74-2960f7820e60">

2023-12-05 07:07 UTC, shankari commented
@drmrd as a temporary workaround while waiting for the permission issues to be resolved, I suggest that we implement:
* build images + future extension to run automated tests on PR
* build + test + push images on branch push and/or tag/release creation

Note that secrets *are* available on push since it is approved code and not a pull request, which can potentially include malicious code.

Yes, "there can be a brief post-merge period during which Docker Compose files will point to images that don't exist in GHCR" but this is a stop-gap anyway and we can revisit what it will look like after all the permissions are finalized and all the images are built in the separate repos.

If we do end up keeping something like this for the long-term, there are workarounds we can consider (e.g. having two environment variables `BUILD_TAG` and `DEPLOY_TAG` and updating them at different times).

2023-12-05 15:46 UTC, drmrd commented
@shankari: All changes are in. Please merge when you're available. 🚀

2023-12-05 22:07 UTC, shankari approved these changes

2023-12-05 22:08 UTC, merged

2023-12-06 03:32 UTC, shankari commented
Filed https://github.com/EVerest/EVerest/issues/119 since the builds are not getting tagged properly