MRE with working OCPP 2.0.1 security profile 1, 2 and 3 (all)
EVerest/everest-demo pull request #31
Opened 2024-03-16 17:51 UTC by sahabulh

Based on Bryan's fix for the [first MRE](https://github.com/EVerest/everest-demo/pull/29). I have just added scripts and databases for all profiles.

2024-03-17 03:13 UTC, shankari commented
@activeshadow  and @sahabulh you need to sign off on your commits. This is required for LFE projects to ensure clear copyright for the generated code https://developercertificate.org/, https://stackoverflow.com/a/1962112

If you want to go back and sign your commits, you can rebase with -s https://stackoverflow.com/a/15667644 or close this PR and submit a new one

> No OCPP logs although the OCPP module reports it is logging messages

Where are you checking the logs? The fact that your command starts with `$` seems to indicate that you are checking on the host and not the container. The code runs in the container so the log is in the container. You need to use `docker cp` to get it out.

2024-03-17 04:03 UTC, shankari requested changes
I am a bit confused. I thought that with the most recent release of EVerest, we still had issues with the connection. These MREs are still using the most recent version, but appear to be passing.

Is it possible to summarize what changes were required to get this to work? It would be helpful both for the review and for the historical record.

I also have some high-level cleanup feedback below.

2024-03-17 13:19 UTC, activeshadow commented on demo-iso15118-2-ac-plus-ocpp201.sp2.sh
> +git clone --branch no-lb https://github.com/activeshadow/maeve-csms.git maeve-csms
@shankari let's just remove this dependency now if no one else is having load balancer issues and I can keep it in place locally for testing until I can debug it specifically on my end.

2024-03-18 02:02 UTC, shankari commented on demo-iso15118-2-ac-plus-ocpp201.sp2.sh
> +git clone --branch no-lb https://github.com/activeshadow/maeve-csms.git maeve-csms
@activeshadow @sahabulh also had some issues with the load balancer. This may also be a linux versus mac issue, although I can't tell without seeing what the error actually is

2024-03-18 15:14 UTC, shankari commented
@sahabulh can you please address the review feedback? Also here's the list of commits that are currently not signed off
<img width="887" alt="Screenshot 2024-03-18 at 8 14 12 AM" src="https://github.com/EVerest/everest-demo/assets/2423263/ab3dcba0-91eb-4d18-93a6-a307aa8b9b96">

2024-03-18 17:17 UTC, sahabulh commented
@shankari This PR is ready to be looked at again

2024-03-18 17:32 UTC, shankari commented
@sahabulh can you please comment on where the EonTI certificates come from? Did you generate them from the root, or are they generated by EonTI? I would like to respond and provide feedback to EonTI on the certificates that they have generated and the ability to use them in software settings

2024-03-18 17:38 UTC, activeshadow commented
> @sahabulh can you please comment on where the EonTI certificates come from? Did you generate them from the root, or are they generated by EonTI? I would like to respond and provide feedback to EonTI on the certificates that they have generated and the ability to use them in software settings [#25 (comment)](https://github.com/EVerest/everest-demo/issues/25#issuecomment-2001084426) [#25 (comment)](https://github.com/EVerest/everest-demo/issues/25#issuecomment-2002308322)

@shankari sorry to jump in this conversation, especially since I'm not answering your EonTI question specifically, but I did want to point out that in general we (@sahabulh and I) did not include anything specific to EonTI in this PR. This PR is still using the same certs as the SP2 demo. If/When the EonTI stuff gets figured out, the plan is to have that in a separate commit/PR to keep things clean.

2024-03-18 17:39 UTC, sahabulh commented
> @sahabulh can you please comment on where the EonTI certificates come from? Did you generate them from the root, or are they generated by EonTI? I would like to respond and provide feedback to EonTI on the certificates that they have generated and the ability to use them in software settings [#25 (comment)](https://github.com/EVerest/everest-demo/issues/25#issuecomment-2001084426) [#25 (comment)](https://github.com/EVerest/everest-demo/issues/25#issuecomment-2002308322)

@shankari Craig is already talking with the EonTi team about this. I don't have the details. But I will let you know what happens.

2024-03-18 17:40 UTC, activeshadow commented
@shankari also worth noting that if you want to test the SP3 demo script locally, you'll need to be sure to change line 34 in the demo script to clone the forked repo and branch this PR is based on instead of the main repo. Just FYSA, though I'm sure you're already aware.

2024-03-18 17:48 UTC, shankari commented
@activeshadow understood. I hijacked this PR a bit because I would really like the response to the EonTI question and I wasn't seeing a response to it otherwise.

@sahabulh so are you saying that Craig provided the EonTI certificates to you? I would just like clarity on where the certificates came from because they do not appear to match the certificates in the Google Drive shared by EonTI. I can go out to EonTI saying that I don't know where the certificates came from, but in general, it is better to provide as much information as possible upfront.

2024-03-18 18:23 UTC, shankari requested changes
@sahabulh Once you revert that change, I am happy to merge this. But when you submit the EonTI PR, I would like to see a description of how the certs are generated. This is an MRE after all so we need to understand all the steps properly!

I also assume you have tested, and am merging optimistically! We can always fix if it turns out that this doesn't work.

2024-03-18 18:23 UTC, shankari commented on manager/config.json
I don't think this change is required since the URL is configured in the DB anyway,

2024-03-18 19:56 UTC, CRR-SNL commented
Certificates we're using come from the CRP PKI prototype instance Sandia has access to under an MOU with SAE. They might differ from those EonTi is providing for NREL testing early next month. BTW I've invited SAE and EonTi leads to join the EVerest General weekly call tomorrow and requested a slot on the agenda for them to share the current situation re: availability of their planned test platform (APIs) and roadmap. 

To move beyond uncertainty/confusion about cert provenance, intended use, etc. I've suggested EVerest modules use a local repository (for now, perhaps APIs later) that supports multiple well-documented cert bundles.

2024-03-18 20:06 UTC, activeshadow commented
@sahabulh you didn't sign off on your most recent commit that reverted the changes to `config.json` per the requested changes. I would suggest just squashing your latest commit with the reverted changes into the first commit in this PR where the changes were originally made and then force pushing to your branch for this PR. I can walk you though the steps if you like. It can be done via an interactive rebase like we did earlier.

2024-03-18 20:20 UTC, sahabulh commented
@activeshadow Sorry, fixed it in a different way. Is it okay?

2024-03-18 20:22 UTC, activeshadow commented
> @activeshadow Sorry, fixed it in a different way. Is it okay?

Yes sir, all good!

2024-03-18 21:43 UTC, sahabulh commented
@activeshadow Respecting your suggestion, I squashed the last commit into the first one using the interactive rebase and then force pushed it.

2024-03-18 21:46 UTC, sahabulh commented
> @sahabulh Once you revert that change, I am happy to merge this. But when you submit the EonTI PR, I would like to see a description of how the certs are generated. This is an MRE after all so we need to understand all the steps properly!
> 
> I also assume you have tested, and am merging optimistically! We can always fix if it turns out that this doesn't work.

Please review again. I reverted the changes to the config file.

2024-03-18 21:46 UTC, activeshadow commented
> @activeshadow Respecting your suggestion, I squashed the last commit into the first one using the interactive rebase and then force pushed it.

Noice! :+1:

2024-03-18 22:55 UTC, shankari commented
@CRR-SNL thank you for that clarification! That explains why I could not find any of these certs in the files provided by EonTI for the PKI testing event.

wrt

> To move beyond uncertainty/confusion about cert provenance, intended use, etc. I've suggested EVerest modules use a local repository (for now, perhaps APIs later) that supports multiple well-documented cert bundles.

The EVerest libevsecurity module supports cert bundles - if you check the script included here, you will see that we upload a cert bundle to the EVSE container and copy the certs to the correct locations. Any arbitrary cert bundle can be supported in the same way.

However, I am not sure that EVerest will want to have multiple cert bundles installed in the EVSE at the same time; in production, an EVSE will have the cert bundle for the CSMS that they are connecting to.

Having said that, from an internoperability perspective, maybe it would be better to have multiple V2G roots in a root bundle to make it easier to switch between networks. To go back to my favorite example of browser + website interop, most browsers will store multiple CA roots, which they keep updated through periodic updates.

Did you mean multiple roots or multiple bundles?

2024-03-19 04:03 UTC, shankari commented
@sahabulh the checks are failing since you renamed device_model_storage_maeve_preconfigured.db to manager/device_model_storage_maeve_sp1.db

Please either restore, or change the manager Dockerfile

2024-03-19 07:20 UTC, sahabulh commented
> @sahabulh the checks are failing since you renamed device_model_storage_maeve_preconfigured.db to manager/device_model_storage_maeve_sp1.db
> 
> Please either restore, or change the manager Dockerfile

Done!

2024-03-19 15:44 UTC, shankari commented
Checks now pass. We should fix the static analysis across all the scripts so that all the checks pass 😄 but that doesn't need to hold up this release.

2024-03-19 15:44 UTC, merged