Impose resource constraints on demos
EVerest/everest-demo pull request #6
Opened 2023-11-17 22:02 UTC by drmrd

As a first step towards emphasizing that EVerest is built for embedded systems, we're adding maximum CPU usage and RAM constraints of 100% (1 core) and 1 GB, respectively, in each demo.

Note that EVerest can run under much more aggressive resource constraints in realistic conditions. See for example [this discussion](https://lists.lfenergy.org/g/everest/topic/101311797#617) from the mailing list for more details. The `manager` containers in our demos require more CPU and memory resources at present due to the inclusion of unoptimized test and simulation modules in these containers. Follow-up work will include a demo where the test and simulation code is isolated into a separate image to provide greater realism.

2023-11-19 17:07 UTC, shankari requested changes
You need to make sure that changes to the docker compose files are consistent.
- The changes to the location of the images here contradicts the ones in https://github.com/EVerest/everest-demo/pull/5, for example
- The images are not the most recent ones

I don't see any other high level issues with this although it is clearly a very preliminary change.

2023-11-19 17:07 UTC, shankari commented on nodered/Dockerfile
> +COPY --chown=node-red:root config /config
can you clarify why we need this?

2023-11-20 17:08 UTC, drmrd commented on nodered/Dockerfile
> +COPY --chown=node-red:root config /config
This is a general improvement that snuck its way into this PR; it isn't necessary for imposing resource constraints.

Currently, if you attempt to modify and redeploy a Node-Red flow in a `nodered` container, the deploy process fails due to permissions not being appropriately set on the config folder. This change allows the `node-red` user to apply your configuration changes.

2023-11-21 05:19 UTC, shankari commented on nodered/Dockerfile
> +COPY --chown=node-red:root config /config
@drmrd can you expand a bit further? My general assumption was that, if there were a new or modified node-red flow, we would just create a new container with the new flow. When would we modify a node-red flow in an existing container? Is this primarily in a dev environment?

2023-11-21 14:01 UTC, couryrr-afs commented on nodered/Dockerfile
> +COPY --chown=node-red:root config /config
@shankari currently no changes can be easily made within the node-red container. While these are labeled demo the users may want to experiment with them after getting them running. This change will allow them to easily do so. This has the added advantage that if those changes are committed, i.e. the node-red config, then they are part of the new image. It will assist in the full lifecycle of these docker images and the demo.

2023-12-06 19:59 UTC, drmrd commented
@shankari: I have another PR ready for you. 😃 

While we're here, there was an interesting discussion at the Weekly Technical Sync on Tuesday that's relevant to improved versions of this demo. Someone had asked about the possibility of extracting EV simulations into their own containers/running them on separate boards, and @corneliusclaussen had an in-depth comprehensive response. The short of it is that

- This is possible but challenging to do right.
- Ultimately there is a desire to create an `ev_manager` process that can operate like the `evse_manager` but independently from an EVSE EVerest stack.
- There is a long-running branch in `everest-core` called [ccc-ev](https://github.com/EVerest/everest-core/tree/ccc-ev) that addresses a lot of this work. (IIRC the "CCC" is due to the branch being developed at a Chaos Computer Club meeting/hackathon.)
- @corneliusclaussen would like to see this branch incorporated into EVerest in the not-too-distant future but is holding off on approaching it again until after [updates to the BSP interface](https://github.com/EVerest/everest-core/pull/379) are completed.

2023-12-06 22:31 UTC, shankari requested changes

2023-12-06 22:31 UTC, shankari commented on README.md
> +The resource constraints for a demo can be changed in its Docker Compose file (the file downloaded in "STEP 1" below).
This is now below STEP 1. And since we now have the wrapper shell script, the docker-compose is now tucked away in a temporary location somewhere. To keep the original "one-line demo" concept, and to make it even better than "change them by editing a file", why not have them be passed in as environment variables?

It looks like

```
CPU='1.0' MEM="1024mb" docker-compose ..
```

should work

https://stackoverflow.com/a/33186458

2023-12-07 16:31 UTC, shankari commented
Since I merged the OCPP change first, the semver needs to be bumped up by 2.

2023-12-07 23:04 UTC, drmrd commented on README.md
> +The resource constraints for a demo can be changed in its Docker Compose file (the file downloaded in "STEP 1" below).
@shankari: I've extracted the resource limits into the `.env` file and provided instructions in the `README.md` for how to customize these values.

2023-12-08 00:43 UTC, shankari approved these changes

2023-12-08 00:51 UTC, shankari approved these changes
I am going to merge this now, but this PR is missing a couple of docker compose files (`automated-tests` and `ocpp16j`). @drmrd, please submit them in a separate PR 😄

2023-12-08 00:51 UTC, merged