Update README.md
EVerest/everest-demo pull request #73
Opened 2024-10-09 14:33 UTC by nserway

Updated the EVerest Demo README to improve readability, set-up instructions, and include mermaid diagrams of the various demonstrations that are included in the repository.

2024-10-14 15:27 UTC, shankari requested changes
@nserway as I have indicated earlier, I would like to see some additional discussion of the rationale behind the PR in the description.
What are the high level changes? 
What was the related design discussion?
*Why* are the changes set up this way?

This is particularly important in this case because the main goal of the rewrite was to **redesign** the user interface and provide a template for future changes to follow.

2024-10-15 13:49 UTC, nserway commented on README.md
> +| **E2E Automated Tests** | Performs an automated test of a full charging session| N/A |
We did not create a mermaid diagram for the E2E tests. Since there isn't a UI associated with the demonstration (or if there is, the demo is not functioning properly) it was difficult to visualize what a diagram would look like.

2024-10-15 13:50 UTC, nserway commented on README.md
> +   - Install [Windows Subsystem for Linux](https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fwindows%2Fwsl%2Finstall&data=05%7C02%7Cnathan.serway%40afs.
I believe this is a function of our AFS machines. I do not believe there is a way around this on our end

2024-10-15 14:04 UTC, nserway commented on README.md
> +   - Note: When runing the demonstrations, use the Docker desktop terminal for the best results. However, demonstration commands can be posted directly into your machine's terminal if running on Wind
1. This note was spun out of a conversation with Katie about the additional functionality of Linux systems (i.e., running a demo script directly in a Linux machine's terminal) I will remove this note for clarity as I do not think it adds significant value to the overall README + created confusion on your review.
_2. See above._ 
3. Just ran a spell check across the whole document + updated!

2024-10-15 14:11 UTC, nserway commented on README.md
> +3. Open the Docker desktop application and navigate to the terminal at the bottom of the screen.
<img width="1792" alt="Screenshot 2024-10-15 at 10 08 54 AM" src="https://github.com/user-attachments/assets/528e0854-417d-4959-83dc-d2503ae043f8">

This is what the application looks like on my end, I paste the Demo Command inside of the terminal to get the containers to spin up. Not sure if that's how all users Docker applications UI looks. 

Additionally, I will remove Linux system notes for clarity since they are causing confusion.

2024-10-15 14:23 UTC, nserway commented on README.md
>  - When running the Basic and ISO 15118-2 AC Charging with OCPP 1.6J CSMS demo, you can open the SteVe wep portal at http://localhost:8180/steve/manager/home. Login with username: admin, password: 123
Would you like me to remove or keep the instructions? The comment is showing as "resolved" on my end. We had a conversation a few weeks ago where we decided to keep the instructions in because most of the Charging Community is still using 1.6

2024-10-15 14:23 UTC, nserway commented on README.md
>    - Note that the OCPP logs are available at `/tmp/everest_ocpp_logs/` on the EVerest manager and can be downloaded using the docker desktop or `docker cp`
Where are the ISO logs stored? Happy to add in that detail once it is confirmed.

2024-10-15 14:26 UTC, nserway commented on README.md
> +   CS -->> EVSE: StartTransaction.conf (Accepted)
The goal of the diagram was to provide a high level (non-granular) illustration of what is being demonstrated across the Demos. I was aiming for a very simplified version of the charging session

2024-10-15 15:49 UTC, nserway commented on README.md
> +   - Install [Windows Subsystem for Linux](https://usg02.safelinks.protection.office365.us/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fwindows%2Fwsl%2Finstall&data=05%7C02%7Cnathan.serway%40afs.
Manually added link w/o "safelink" addition

2024-10-15 15:54 UTC, nserway commented on README.md
>  - When running the Basic and ISO 15118-2 AC Charging with OCPP 1.6J CSMS demo, you can open the SteVe wep portal at http://localhost:8180/steve/manager/home. Login with username: admin, password: 123
removed reference to 1.6

2024-10-15 16:03 UTC, nserway commented on README.md
> +export EVEREST_MANAGER_CPUS='2.0' EVEREST_MANAGER_MEMORY='1536mb'
Validated by updating the values from the terminal and validating the update and then reverting to the values in the .env file.

2024-10-15 16:24 UTC, shankari commented
@nserway can you please have the tech team review this before sending it back to me for review? Some of your comments have fairly simple technical solutions, and it would be the most effective use of my time to have them addressed first.

2024-10-15 16:58 UTC, shankari commented on README.md
> +3. Open the Docker desktop application and navigate to the terminal at the bottom of the screen.
@nserway "works for me" is not a good basis for demo instructions. I assume you are using Windows for this. Even if it works on Windows, that is 1/3 of the common OSes.

You should retain the instructions that work for the 2/3 case, which is to run it from the terminal.

2024-10-15 16:58 UTC, shankari commented on README.md
> +   - Note: When runing the demonstrations, use the Docker desktop terminal for the best results. However, demonstration commands can be posted directly into your machine's terminal if running on Wind
I am arguing for *not* using the docker desktop terminal and instead, using the command line.

2024-10-15 17:07 UTC, shankari commented on README.md
> +| **E2E Automated Tests** | Performs an automated test of a full charging session| N/A |
The mermaid diagram is not related to the UI. The mermaid diagram is set up to understand how the various software modules communicate with each other, and the E2E test clearly has modules working together for the testing.

2024-10-15 17:08 UTC, shankari commented on README.md
>    - Note that the OCPP logs are available at `/tmp/everest_ocpp_logs/` on the EVerest manager and can be downloaded using the docker desktop or `docker cp`
They are in fact stored as part of every EVerest run (I don't remember where OTOH, but it is in the startup logs). 
Please look at the logs yourself or check with the tech team.

2024-10-15 17:09 UTC, shankari commented on README.md
> +export EVEREST_MANAGER_CPUS='2.0' EVEREST_MANAGER_MEMORY='1536mb'
how did you validate the update?

2024-10-15 17:20 UTC, shankari commented on README.md
> +   CS -->> EVSE: StartTransaction.conf (Accepted)
If we want a high-level description, I would avoid using specific ISO names (`StartTransactionReq`) because that implies that those are the messages getting sent. You should instead use a high-level text description.

2024-10-15 17:26 UTC, nserway commented on README.md
> +   Note over EV,EVSE: Connection Establishment
Yes, the PP and CP checks are a part of this charging session as defined in the ISO 15118-2 documentation. https://www.typhoon-hil.com/documentation/typhoon-hil-software-manual/References/iso15118_protocol.html. We will make changes in the README to cite this documentation.

2024-11-02 22:43 UTC, shankari commented
This is not great, but it is an improvement over what we had before, so I am going ahead and checking this in now.

2024-11-02 22:43 UTC, merged